/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_jarlen_phototedit_filter_NativeFilter */

#ifndef _Included_cn_jarlen_phototedit_filter_NativeFilter
#define _Included_cn_jarlen_phototedit_filter_NativeFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_jarlen_phototedit_filter_NativeFilter
 * Method:    ToGray
 * Signature: ([IIIF)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_jarlen_phototedit_filter_NativeFilter_ToGray
  (JNIEnv *, jobject, jintArray, jint, jint, jfloat);

/*
 * Class:     cn_jarlen_phototedit_filter_NativeFilter
 * Method:    ToMosatic
 * Signature: ([IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_jarlen_phototedit_filter_NativeFilter_ToMosatic
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

/*
 * Class:     cn_jarlen_phototedit_filter_NativeFilter
 * Method:    ToBrown
 * Signature: ([IIIF)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_jarlen_phototedit_filter_NativeFilter_ToBrown
  (JNIEnv *, jobject, jintArray, jint, jint, jfloat);

/*
 * Class:     cn_jarlen_phototedit_filter_NativeFilter
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_jarlen_phototedit_filter_NativeFilter_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
